### ISSUE TITLE
Caused by: java.net.UnknownHostException: apiserver.cluster.local: Name or service not known

### ISSUE THREAD

**Issue by ganganxiaojiu** [nineinfra/kubectl-nine#10]
$ kubectl nine tpcds nine-test -n dwh -g -d tpcds_nine01 --scale 1024 -p 20
$ echo $KUBECONFIG
/srv/kubernetes/kubeconfig

$ cat /srv/kubernetes/kubeconfig |grep apiserver
    server: https://apiserver.cluster.local:6443

**Comment by nineinfra** [comment]
resolve apiserver.cluster.local in coredns or change to host ip
